version: "3"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  postgres:
    image: postgres-1
    environment:
      POSTGRES_DB: "kinoteatr"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "114860"
    ports:
      - "5432:5432"