CREATE TABLE public.card
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT,
    card_date   FLOAT,
    card_number VARCHAR(255),
    card_secret INTEGER,
    CONSTRAINT pk_card PRIMARY KEY (id)
);

ALTER TABLE public.card
    ADD CONSTRAINT FK_CARD_ON_USER FOREIGN KEY (user_id) REFERENCES public.t_user (id);